export TERM="xterm-256color"
export ZSH="/home/cainchen/.oh-my-zsh"
ZSH_THEME="powerlevel9k/powerlevel9k"
plugins=(git pip vi-mode zsh-autosuggestions zsh-syntax-highlighting)

POWERLEVEL9K_COLOR_SCHEME='bright'

POWERLEVEL9K_CONTEXT_TEMPLATE="%n@"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(ssh context dir dir_writable vcs)
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs ip vpn_ip os_icon)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status ram os_icon)
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='black'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='178'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="blue"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="255"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="red"

#POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
#POWERLEVEL9K_TIME_BACKGROUND='255'
#POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='245'
#POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='black'

POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_to_last"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true

source $ZSH/oh-my-zsh.sh
